Repository exercism/python, pull requests merged in 2018-12, with the labels that each got.

#1611 bank-account: remove redundant iteration
  exercises/bank-account/bank_account_test.py
Labels: concurrency, enhancement

#1626 test/check_exercises.py: improve portability
  test/check-exercises.py
Labels: enhancement

#1633 Copy Ruby Track's core progression
  config.json
Labels: enhancement

#1634 dnd-character: fix minor typo in comment
  exercises/dnd-character/dnd_character_test.py
Labels: bug

#1637 travis: verify READMEs contain latest .meta contents
  .travis.yml
  bin/check-readmes.sh
Labels: enhancement

#1638 scale-generator: update tests to v2.0.0
  exercises/scale-generator/example.py
  exercises/scale-generator/scale_generator.py
  exercises/scale-generator/scale_generator_test.py
Labels: enhancement
