Repository exercism/python, pull requests merged in 2018-04, with the labels that each got.

#1360 go-counting: adapt tests to canonical data v1.0.0
  exercises/go-counting/example.py
  exercises/go-counting/go_counting.py
  exercises/go-counting/go_counting_test.py
Labels: awaiting review, bug

#1359 sgf-parsing: implement exercise
  config.json
  exercises/sgf-parsing/README.md
  exercises/sgf-parsing/example.py
  exercises/sgf-parsing/sgf_parsing.py
  exercises/sgf-parsing/sgf_parsing_test.py
Labels: awaiting review, enhancement

#1299 lens-person: forego exercise
  config.json
Labels: awaiting review

#1260 Implement exercise bank-account
  config.json
  exercises/bank-account/README.md
  exercises/bank-account/bank_account.py
  exercises/bank-account/bank_account_test.py
  exercises/bank-account/example.py
Labels: awaiting review, pinned

#1164 pascals-triangle: update tests to canonical-data v1.2.0
  exercises/pascals-triangle/example.py
  exercises/pascals-triangle/pascals_triangle.py
  exercises/pascals-triangle/pascals_triangle_test.py
Labels: awaiting review, enhancement

#1355 Curriculum
  config.json
Labels: awaiting review, enhancement, maintainer action required

#1358 alphametics: mark computationally intensive test as extra-credit
  exercises/alphametics/alphametics_test.py
  test/check-exercises.py
Labels: awaiting review

#1346 react: Update tests to v2.0.0
  exercises/react/example.py
  exercises/react/react.py
  exercises/react/react_test.py
Labels: pinned
