Repository exercism/python, pull requests merged in 2019-06, with the labels that each got.

#1818 README.md: Remove references to Python 2.7 from README.md (#1704)
  README.md
Labels: drop-python2

#1822 TESTS.md: Remove Python 2.7 references from TESTS.md
  docs/TESTS.md
Labels: drop-python2

#1823 LEARNING.md: Remove Python 2.7 references from LEARNING.md
  docs/LEARNING.md
Labels: drop-python2

#1811 sieve: sync with canonical data
  exercises/sieve/example.py
  exercises/sieve/sieve.py
  exercises/sieve/sieve_test.py
Labels: canonical-sync

#1812 Nth prime: sync expected test results and input data with problem-specifications
  exercises/nth-prime/example.py
  exercises/nth-prime/nth_prime.py
  exercises/nth-prime/nth_prime_test.py
Labels: canonical-sync

#1813 secret handshake: sync with canonical data
  exercises/secret-handshake/example.py
  exercises/secret-handshake/secret_handshake.py
  exercises/secret-handshake/secret_handshake_test.py
Labels: canonical-sync

#1815 Prime factors: sync expected test results and input data with problem-specifications
  exercises/prime-factors/example.py
  exercises/prime-factors/prime_factors.py
  exercises/prime-factors/prime_factors_test.py
Labels: canonical-sync

#1817 Raindrops: sync expected test results and input data with problem-specifications.
  exercises/raindrops/example.py
  exercises/raindrops/raindrops.py
  exercises/raindrops/raindrops_test.py
Labels: canonical-sync

#1819 Rectangles: sync expected test results and input data with problem-specifications.
  exercises/rectangles/example.py
  exercises/rectangles/rectangles.py
  exercises/rectangles/rectangles_test.py
Labels: canonical-sync

#1820 roman-numerals: sync expected test results and input data with problem-specifications.
  exercises/roman-numerals/example.py
  exercises/roman-numerals/roman_numerals.py
  exercises/roman-numerals/roman_numerals_test.py
Labels: canonical-sync

#1824 reverse-string: update tests to v1.2.0
  exercises/reverse-string/reverse_string_test.py
Labels: canonical-sync

#1825 luhn: update tests to v1.6.1
  exercises/luhn/example.py
  exercises/luhn/luhn.py
  exercises/luhn/luhn_test.py
Labels: canonical-sync

#1816 Pythagorean triplet: sync expected test results and input data with problem-specifications.
  exercises/pythagorean-triplet/example.py
  exercises/pythagorean-triplet/pythagorean_triplet.py
  exercises/pythagorean-triplet/pythagorean_triplet_test.py
Labels: canonical-sync

#1814 Palindrome products: sync expected test results and input data with problem-specifications.
  exercises/palindrome-products/example.py
  exercises/palindrome-products/palindrome_products.py
  exercises/palindrome-products/palindrome_products_test.py
Labels: canonical-sync

#1809 sublists: sync with canonical data
  exercises/sublist/example.py
  exercises/sublist/sublist.py
  exercises/sublist/sublist_test.py
Labels: canonical-sync

#1830 Do not unlock side exercises with hello-world
  config.json
Labels: pinned
