Repository exercism/python, pull requests merged in 2019-03, with the labels that each got.

#1689 Track Restructure (First pass)
  config.json
Labels: pinned, track-anatomy

#1696 hangman: winning on last guess still counts as a win
  exercises/hangman/example.py
  exercises/hangman/hangman.py
  exercises/hangman/hangman_test.py
Labels: enhancement

#1695 high-scores: add `classes` topic
  config.json
Labels: enhancement

#1711 Remove Python2.7 from Travis build matrix
  .travis.yml
Labels: drop-python2

#1715 Update check-exercises.py to Python 3
  test/check-exercises.py
Labels: drop-python2

#1710 Travis: enforce configlet fmt
  .travis.yml
Labels: enhancement

#1719 Create CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement
