Repository exercism/python, pull requests merged in 2021-05, with the labels that each got.

#2419 🤖 Add fetch configlet script(s) to CODEOWNERS file
  .github/CODEOWNERS
Labels: v3-migration 🤖

#2440 🤖 Remove `online_editor.ace_editor_language` key
  config.json
Labels: v3-migration 🤖

#2441 🤖 Add labels append file
  .appends/.github/labels.yml
Labels: v3-migration 🤖

#2435 [Little Sisters Essay (String Methods)] Added code examples to introduction doc.
  exercises/concept/little-sisters-essay/.docs/introduction.md
Labels: improve exercise 💖

#2434 Edited strings about.md file.
  concepts/strings/about.md
Labels: improve reference docs 💖, reputation/contributed_code/minor

#2430 Concept Conditionals Add Files
  concepts/conditionals/.meta/config.json
  concepts/conditionals/about.md
  concepts/conditionals/introduction.md
  concepts/conditionals/links.json
Labels: improve documentation 💖, reputation/contributed_code/major

#2442 [Little Sisters Vocab] Update introduction.md to close Code Block
  exercises/concept/little-sisters-vocab/.docs/introduction.md
Labels: reputation/contributed_code/minor

#2444 Update config.json File
  config.json
Labels: reputation/contributed_code/minor
