Repository exercism/python, pull requests merged in 2021-07, with the labels that each got.

#2460 Fix Missing EndQuote on Line 163
  .appends/.github/labels.yml
Labels: x:size/tiny

#2464 🤖 Update name of `dnd-character` exercise
  config.json
Labels: v3-migration 🤖

#2463 🤖 Simplify `hello-world` stub
  exercises/practice/hello-world/hello_world.py
Labels: v3-migration 🤖

#2474 Delete exercise_readme.go.tmpl
  config/exercise_readme.go.tmpl
Labels: x:size/tiny

#2475 Moved `exercises/shared` .md docs into `exercises/shared/.docs` Directory.
  exercises/shared/.docs/help.md
  exercises/shared/.docs/tests.md
Labels: x:size/small
