Repository exercism/python, pull requests merged in 2021-09, with the labels that each got.

#2510 Added missing TODO for 'PREPARATION_TIME' constant.
  exercises/concept/guidos-gorgeous-lasagna/lasagna.py
Labels: x:size/small

#2519 Refreshed RESOURCES.md
  docs/RESOURCES.md
Labels: x:size/small

#2525 Update instructions.md
  exercises/concept/chaitanas-colossal-coaster/.docs/instructions.md
Labels: x:size/small

#2529 Card-Games: Fix return types and descriptions in the docstring
  exercises/concept/card-games/.docs/instructions.md
  exercises/concept/card-games/.meta/exemplar.py
  exercises/concept/card-games/lists.py
Labels: x:size/medium

#2531 Minor change in instructions
  exercises/concept/chaitanas-colossal-coaster/.docs/instructions.md
Labels: x:size/tiny

#2546 Fix typo in markdown for a link
  docs/TESTS.md
Labels: x:size/small

#2552 Fixed numbers_to_cube example.
  concepts/lists/about.md
Labels: x:size/small

#2559 [Python (PyTest)] Added PyTest ini File to Register Task Custom Mark
  pytest.ini
Labels: x:size/small

#2600 Adjust Flake8 Line Length to 110 Char +/- 10 Chars
  .flake8
Labels: x:size/small

#2603 Changed Names of Test Classes to be ExerciseNameTest
  exercises/concept/black-jack/black_jack_test.py
  exercises/concept/card-games/lists_test.py
  exercises/concept/chaitanas-colossal-coaster/list_methods_test.py
  exercises/concept/currency-exchange/exchange_test.py
  exercises/concept/ghost-gobble-arcade-game/arcade_game_test.py
  exercises/concept/inventory-management/dicts_test.py
  exercises/concept/little-sisters-essay/string_methods_test.py
  exercises/concept/little-sisters-vocab/strings_test.py
  exercises/concept/log-levels/enums_test.py
  exercises/concept/making-the-grade/results.json
  exercises/concept/meltdown-mitigation/conditionals_test.py
  exercises/concept/pretty-leaflet/string_formatting_test.py
  exercises/concept/restaurant-rozalynn/none_test.py
  exercises/concept/tisbury-treasure-hunt/tuples_test.py
Labels: x:size/large

#2607 Update instructions.md
  exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md
Labels: x:size/small

#2612 Correct fail_safe docstring
  exercises/concept/meltdown-mitigation/conditionals.py
Labels: x:size/small

#2615 [Cater-Waiter]: Reduced the Overall Number of Set Tests to 82
  exercises/concept/cater-waiter/sets_test.py
  exercises/concept/cater-waiter/sets_test_data.py
Labels: x:size/large
