Repository exercism/python, pull requests merged in 2021-11, with the labels that each got.

#2710 Updated Readme to fix hanging line.
  README.md
Labels: x:size/small

#2723 🤖 Remove obsolete `maintainers.json` file
  .github/CODEOWNERS
  config/maintainers.json
Labels: x:size/tiny

#2724 Removed excess `<br>` from Greeting
  .github/pr-commenter.yml
Labels: x:size/tiny

#2735 alphametics: Fix typo
  exercises/practice/alphametics/.meta/example.py
Labels: x:size/tiny

#2759 [Transpose]: Update from Problem Specifications
  exercises/practice/transpose/.meta/template.j2
  exercises/practice/transpose/.meta/tests.toml
  exercises/practice/transpose/transpose_test.py
Labels: x:size/small

#2758 [Tournament]: Update from Problem Specifications
  exercises/practice/tournament/.meta/template.j2
  exercises/practice/tournament/.meta/tests.toml
  exercises/practice/tournament/tournament_test.py
Labels: x:size/small

#2757 [Sublist]: Update from Problem Specifications
  exercises/practice/sublist/.docs/instructions.md
  exercises/practice/sublist/.meta/template.j2
  exercises/practice/sublist/.meta/tests.toml
  exercises/practice/sublist/sublist_test.py
Labels: x:size/small

#2756 [Resistor-Color-Duo]: Update from Problem Specifications
  exercises/practice/resistor-color-duo/.docs/instructions.md
  exercises/practice/resistor-color-duo/.meta/template.j2
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/resistor_color_duo_test.py
Labels: x:size/small

#2755 [Rational-Numbers]: Update from Problem Specifications
  exercises/practice/rational-numbers/.docs/instructions.md
  exercises/practice/rational-numbers/.meta/tests.toml
  exercises/practice/rational-numbers/rational_numbers_test.py
Labels: x:size/small

#2754 [Prime-Factors]: Update from Problem Specifications
  exercises/practice/prime-factors/.docs/instructions.md
  exercises/practice/prime-factors/.meta/template.j2
  exercises/practice/prime-factors/.meta/tests.toml
  exercises/practice/prime-factors/prime_factors.py
  exercises/practice/prime-factors/prime_factors_test.py
Labels: x:size/small

#2753 [Markdown]: Update from Problem Specifications
  exercises/practice/markdown/.meta/template.j2
  exercises/practice/markdown/.meta/tests.toml
  exercises/practice/markdown/markdown_test.py
Labels: x:size/small

#2751 [Luhn]: Update from Problem Specifications
  exercises/practice/luhn/.docs/instructions.md
  exercises/practice/luhn/.meta/template.j2
  exercises/practice/luhn/.meta/tests.toml
  exercises/practice/luhn/luhn_test.py
Labels: x:size/small

#2750 [Kindergarten-Garden]: Update from Problem Specifications
  exercises/practice/kindergarten-garden/.meta/template.j2
  exercises/practice/kindergarten-garden/.meta/tests.toml
  exercises/practice/kindergarten-garden/kindergarten_garden_test.py
Labels: x:size/small

#2749 [Isogram]: Update from Problem Specifications
  exercises/practice/isogram/.docs/instructions.md
  exercises/practice/isogram/.meta/template.j2
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/isogram/isogram_test.py
Labels: x:size/small

#2748 [High-Scores]: Update from Problem Specifications
  exercises/practice/high-scores/.meta/example.py
  exercises/practice/high-scores/.meta/template.j2
  exercises/practice/high-scores/.meta/tests.toml
  exercises/practice/high-scores/high_scores.py
  exercises/practice/high-scores/high_scores_test.py
Labels: x:size/small

#2747 [Hamming]: Update from Problem Specifications
  exercises/practice/hamming/.docs/instructions.md
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hamming/hamming_test.py
Labels: x:size/small

#2739 [Anagram] : Update from Problem Specifications
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram_test.py
Labels: x:size/small

#2740 [Book-Store]: Update from Problem Specifications
  exercises/practice/book-store/.docs/instructions.md
  exercises/practice/book-store/.meta/tests.toml
  exercises/practice/book-store/book_store_test.py
Labels: x:size/small

#2741 [Change]: Update from Problem Specifications
  exercises/practice/change/.meta/tests.toml
  exercises/practice/change/change_test.py
Labels: x:size/small

#2743 [Diffie-Hellman]: Update from Problem Specifications
  exercises/practice/diffie-hellman/.meta/template.j2
  exercises/practice/diffie-hellman/.meta/tests.toml
  exercises/practice/diffie-hellman/diffie_hellman_test.py
Labels: x:size/small

#2744 [Forth]: Update from Problem Specifications
  exercises/practice/forth/.meta/tests.toml
  exercises/practice/forth/forth_test.py
Labels: x:size/small

#2752 Remove duplicate "to"
  exercises/concept/little-sisters-vocab/.docs/instructions.md
Labels: x:size/small

#2763 [Currency Exchange & Tisbury]: Fixed Hint Files
  exercises/concept/currency-exchange/.docs/hints.md
  exercises/concept/tisbury-treasure-hunt/.docs/hints.md
Labels: x:size/small

#2764 Corrected Exercsim Spelling Error
  README.md
Labels: x:size/tiny

#2777 [Issue Auto-Responder]: Small Markdown Updates to Correct Rendering.
  .github/issue-comment.md
Labels: x:size/tiny

#2778 [TESTING Docs]: Added intro and a few suggestions.
  docs/TESTS.md
Labels: x:size/small

#2785 [PR Auto-Comments]: Will the teeny-tiny typo madness never end??
  .github/pr-commenter.yml
Labels: x:size/tiny

#2787 [Linting]: Lint practice stub files (1 / ?)
  exercises/practice/accumulate/.meta/example.py
  exercises/practice/affine-cipher/.meta/example.py
  exercises/practice/all-your-base/.meta/example.py
  exercises/practice/allergies/.meta/example.py
  exercises/practice/alphametics/.meta/example.py
  exercises/practice/armstrong-numbers/.meta/example.py
  exercises/practice/atbash-cipher/.meta/example.py
  exercises/practice/beer-song/.meta/example.py
  exercises/practice/binary-search-tree/.meta/example.py
  exercises/practice/binary-search-tree/binary_search_tree.py
  exercises/practice/binary-search/.meta/example.py
  exercises/practice/binary/.meta/example.py
Labels: x:size/large

#2791 [Linting]: Lint practice stub files (4 / ?)
  exercises/practice/go-counting/.meta/example.py
  exercises/practice/grade-school/.meta/example.py
  exercises/practice/grains/.meta/example.py
  exercises/practice/grep/.meta/example.py
  exercises/practice/hamming/.meta/example.py
  exercises/practice/hangman/.meta/example.py
  exercises/practice/hangman/hangman.py
  exercises/practice/hexadecimal/.meta/example.py
  exercises/practice/house/.meta/example.py
  exercises/practice/isogram/.meta/example.py
  exercises/practice/kindergarten-garden/.meta/example.py
  exercises/practice/knapsack/.meta/example.py
Labels: x:size/large

#2790 [Linting]: Lint practice stub files (3 / ?)
  exercises/practice/darts/.meta/example.py
  exercises/practice/diffie-hellman/.meta/example.py
  exercises/practice/dnd-character/.meta/example.py
  exercises/practice/dominoes/.meta/example.py
  exercises/practice/dot-dsl/.meta/example.py
  exercises/practice/error-handling/.meta/example.py
  exercises/practice/etl/.meta/example.py
  exercises/practice/food-chain/.meta/example.py
  exercises/practice/forth/.meta/example.py
Labels: x:size/medium

#2789 [Linting]: Lint practice stub files (2 / ?)
  exercises/practice/book-store/.meta/example.py
  exercises/practice/bowling/.meta/example.py
  exercises/practice/change/.meta/example.py
  exercises/practice/circular-buffer/.meta/example.py
  exercises/practice/clock/.meta/example.py
  exercises/practice/collatz-conjecture/.meta/example.py
  exercises/practice/complex-numbers/.meta/example.py
  exercises/practice/connect/.meta/example.py
  exercises/practice/crypto-square/.meta/example.py
  exercises/practice/custom-set/.meta/example.py
Labels: x:size/large

#2797 [Prime Factors]: Solution left in Stub File
  exercises/practice/prime-factors/prime_factors.py
Labels: x:size/small

#2801 [Automation]: Fixing some bots :P
  .github/issue-comment.md
  .github/pr-commenter.yml
Labels: x:type/ci, x:size/tiny

#2806 Copy `pytest.ini` to `exercises/shared` for Future Download via Exercism CLI
  exercises/shared/pytest.ini
Labels: x:size/tiny

#2809 [Linting]: Lint practice stub files (8 / 8)
  exercises/practice/tournament/.meta/example.py
  exercises/practice/tree-building/.meta/example.py
  exercises/practice/triangle/.meta/example.py
  exercises/practice/trinary/.meta/example.py
  exercises/practice/twelve-days/.meta/example.py
  exercises/practice/two-bucket/.meta/example.py
  exercises/practice/two-fer/.meta/example.py
  exercises/practice/variable-length-quantity/.meta/example.py
  exercises/practice/word-count/.meta/example.py
  exercises/practice/word-search/.meta/example.py
  exercises/practice/wordy/.meta/example.py
  exercises/practice/yacht/.meta/example.py
  exercises/practice/zebra-puzzle/.meta/example.py
Labels: x:size/large
