Repository exercism/python, pull requests merged in 2022-04, with the labels that each got.

#2997 [Darts]: Fixes for reflinks and nested bullets
  exercises/practice/darts/.docs/hints.md
Labels: x:size/small

#3014 [Book Store]: Updated Tests from canonical data & Regenned Test Cases
  exercises/practice/book-store/book_store_test.py
Labels: x:size/small

#3015 [Functools Concept]:Update Contributors & Blurb
  concepts/functools/.meta/config.json
Labels: x:size/small

#2991 [Clock] Added `classes` as a Prerequisite
  config.json
Labels: x:size/small

#3020 [Darts]: Restore Nested Bullets
  exercises/practice/darts/.docs/hints.md
Labels: x:rep/small

#3022 admonition typo.
  docs/TOOLS.md
Labels: x:size/tiny
