Repository exercism/python, pull requests merged in 2022-01, with the labels that each got.

#2822 Fixed broken img ref (it was pointing to a private repo)
  reference/track_exercises_overview.md
Labels: x:size/small

#2832 [Yacht] Removed Deprecated Python 2.x Stub Note
  exercises/practice/yacht/yacht.py
Labels: x:size/small

#2843 [ISBN-Verifier] Test File Committed at wrong level.
  isbn_verifier_test.py
Labels: x:size/tiny

#2842 [ISBN-Verifier]: Instructions Accidentally Committed at wrong level
  instructions.md
Labels: x:size/small

#2851 Update sets.py
  exercises/concept/cater-waiter/sets.py
Labels: x:size/medium

#2852 Update exemplar.py
  exercises/concept/cater-waiter/.meta/exemplar.py
Labels: x:size/small

#2853 [Tisbury Treasure Hunt] Correct Mis-Match Between Hint Title & Task Title
  exercises/concept/tisbury-treasure-hunt/.docs/hints.md
Labels: x:size/small

#2867 Update instructions.md
  exercises/concept/black-jack/.docs/instructions.md
Labels: x:size/small

#2866 Update black_jack.py
  exercises/concept/black-jack/black_jack.py
Labels: x:size/small

#2870 ghost-gobble-arcade_game: Fixed typos in hints.md
  exercises/concept/ghost-gobble-arcade-game/.docs/hints.md
Labels: x:size/small
