Repository exercism/python, pull requests merged in 2022-06, with the labels that each got.

#2838 [New Concept]: Decorators
  concepts/decorators/about.md
Labels: x:size/large

#3125 [Loops Concept]: Fixed Broken StopIteration Link in `about.md`
  concepts/loops/about.md
Labels: x:rep/small

#3126 Correct config.json link to python
  README.md
Labels: x:rep/tiny

#3128 [Twelve Days]: Corrected Markdown Header Tags in `hints.md` File
  exercises/practice/twelve-days/.docs/hints.md
Labels: x:rep/small

#3127 [Simple Linked List]: Moved hints.md from .meta to .docs to fix rendering on site.
  exercises/practice/simple-linked-list/.docs/hints.md
Labels: x:rep/small
