Repository exercism/python, pull requests merged in 2022-05, with the labels that each got.

#3037 [Pangram]: Synced Instructions to Problem Specifications.
  exercises/practice/pangram/.docs/instructions.md
Labels: x:rep/small

#3032 [Twelve Days]: Sync Exercise Instructions with Problem-Specifications
  exercises/practice/twelve-days/.docs/instructions.md
Labels: x:rep/small

#3034 [Bank Account]: Synced Instructions to Problem Specs.
  exercises/practice/bank-account/.docs/instructions.md
Labels: x:rep/small

#3033 [Acronym]: Synced Instructions From Problem Specifications.
  exercises/practice/acronym/.docs/instructions.md
Labels: x:rep/small

#3038 [Rational Numbers]: Synced Exercise Instructions to Problem Specifications
  exercises/practice/rational-numbers/.docs/instructions.md
Labels: x:rep/small

#3035 [Darts]: Synced Instructions to Problem Specifications
  exercises/practice/darts/.docs/instructions.md
Labels: x:rep/small

#3039 [Rectangles]: Synced Instructions to Problem Specifications
  exercises/practice/rectangles/.docs/instructions.md
Labels: x:rep/tiny

#3040 [Secret Handshake]: Synced Instructions to Problem Specifications
  exercises/practice/secret-handshake/.docs/instructions.md
Labels: x:rep/small

#3047 [Yacht]: Synced Exercise to Problem Specifications
  exercises/practice/yacht/.meta/tests.toml
  exercises/practice/yacht/yacht_test.py
Labels: x:rep/small

#3046 [Word Count]: Synced Exercise to Problem Specifications
  exercises/practice/word-count/.meta/tests.toml
  exercises/practice/word-count/word_count_test.py
Labels: x:rep/small

#3044 [Phone Number]: Synced Exercise to Problem Specifications
  exercises/practice/phone-number/.meta/tests.toml
  exercises/practice/phone-number/phone_number_test.py
Labels: x:rep/small

#3056 Correct 2nd-Level Header So Website Display Works
  exercises/practice/gigasecond/.docs/hints.md
Labels: x:rep/tiny

#3026 [Simple Linked List]: Added instruction append and hints
  exercises/practice/simple-linked-list/.docs/instructions.append.md
  exercises/practice/simple-linked-list/.meta/hints.md
Labels: x:rep/large

#3024 Removed mention of non-affiliation
  docs/TOOLS.md
Labels: x:size/tiny, documentation 📚, enhancement 🦄 ⭐, x:rep/tiny

#3060 [Simple Linked List]: Correction to URL for SVG Diagrams
  exercises/practice/simple-linked-list/.docs/instructions.append.md
Labels: x:rep/tiny

#3061 [Simple Linked List]: Diagram URL in Hints File
  exercises/practice/simple-linked-list/.meta/hints.md
Labels: x:rep/tiny

#3062 Changed URL for Diagrams to Satisfy CORS
  exercises/practice/simple-linked-list/.docs/instructions.append.md
Labels: x:rep/tiny

#3063 Change URL for Linked List Diagram
  exercises/practice/simple-linked-list/.meta/hints.md
Labels: x:rep/tiny

#3051 [New Concept]: Recursion
  concepts/recursion/.meta/config.json
  concepts/recursion/about.md
  concepts/recursion/introduction.md
  concepts/recursion/links.json
  config.json
Labels: x:rep/large

#3057 [Python Track Syllabus]: Track Re-Ordering
  config.json
Labels: x:rep/massive
