Repository exercism/python, pull requests merged in 2023-08, with the labels that each got.

#3488 Use `assets.exercism.org` subdomain
  exercises/practice/killer-sudoku-helper/.docs/instructions.md
  exercises/practice/simple-linked-list/.docs/hints.md
  exercises/practice/simple-linked-list/.docs/instructions.append.md
Labels: x:size/tiny

#3490 Fix link rendering
  exercises/practice/atbash-cipher/.approaches/introduction.md
  exercises/practice/robot-name/.approaches/introduction.md
Labels: x:rep/small

#3493 another typo
  exercises/practice/atbash-cipher/.approaches/introduction.md
Labels: x:rep/tiny
