Repository exercism/python, pull requests merged in 2023-07, with the labels that each got.

#3453 [Cater-Waiter and Sets]: Code Example Fixes
  concepts/sets/about.md
  exercises/concept/cater-waiter/.docs/introduction.md
Labels: x:rep/tiny

#3435 Removed footer macros, regen tests, all still pass
  exercises/practice/two-fer/.meta/template.j2
  exercises/practice/two-fer/two_fer_test.py
  exercises/practice/word-count/.meta/template.j2
  exercises/practice/word-count/word_count_test.py
  exercises/practice/word-search/.meta/template.j2
  exercises/practice/word-search/word_search_test.py
  exercises/practice/yacht/.meta/template.j2
  exercises/practice/yacht/yacht_test.py
  exercises/practice/zebra-puzzle/.meta/template.j2
  exercises/practice/zebra-puzzle/zebra_puzzle_test.py
  exercises/practice/zipper/.meta/template.j2
  exercises/practice/zipper/zipper_test.py
Labels: do not merge 🚧

#3437 Remove Python 2 references from the track
  concepts/comparisons/about.md
  concepts/string-formatting/about.md
  docs/ABOUT.md
  docs/INSTALLATION.md
  exercises/concept/black-jack/.docs/introduction.md
  exercises/practice/circular-buffer/.meta/example.py
  exercises/practice/pythagorean-triplet/.meta/template.j2
  exercises/practice/pythagorean-triplet/pythagorean_triplet_test.py
  exercises/practice/sublist/sublist.py
  pylintrc
  reference/exercise-concepts/rna-transcription.md
Labels: do not merge 🚧

#3423 Synced `instructions.md` & `introduction.md` Files from Problem Specifications
  exercises/practice/accumulate/.docs/instructions.md
  exercises/practice/binary-search/.docs/instructions.md
  exercises/practice/binary/.docs/instructions.md
  exercises/practice/book-store/.docs/instructions.md
  exercises/practice/bowling/.docs/instructions.md
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/error-handling/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/hexadecimal/.docs/instructions.md
  exercises/practice/killer-sudoku-helper/.docs/instructions.md
  exercises/practice/linked-list/.docs/instructions.md
  exercises/practice/nucleotide-count/.docs/instructions.md
  exercises/practice/octal/.docs/instructions.md
  exercises/practice/pangram/.docs/instructions.md
  exercises/practice/pangram/.docs/introduction.md
  exercises/practice/parallel-letter-frequency/.docs/instructions.md
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/saddle-points/.docs/instructions.md
  exercises/practice/saddle-points/.docs/introduction.md
  exercises/practice/secret-handshake/.docs/instructions.md
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/strain/.docs/instructions.md
  exercises/practice/sum-of-multiples/.docs/instructions.md
  exercises/practice/trinary/.docs/instructions.md
  exercises/practice/two-fer/.docs/instructions.md
Labels: do not merge 🚧

#3434 Remove footer macros, regen tests, all still pass
  exercises/practice/knapsack/.meta/template.j2
  exercises/practice/knapsack/knapsack_test.py
  exercises/practice/leap/.meta/template.j2
  exercises/practice/leap/leap_test.py
  exercises/practice/list-ops/.meta/template.j2
  exercises/practice/list-ops/list_ops_test.py
  exercises/practice/matching-brackets/.meta/template.j2
  exercises/practice/matching-brackets/matching_brackets_test.py
  exercises/practice/pangram/.meta/template.j2
  exercises/practice/pangram/pangram_test.py
Labels: do not merge 🚧

#3464 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#3471 [Track Config]: Removed Yacht from bools association and pushed order to later in track.
  config.json
Labels: x:rep/small

#3474 Roadmap Updates
  concepts/dataclasses/.meta/config.json
  concepts/dataclasses/about.md
  concepts/dataclasses/introduction.md
  concepts/dataclasses/links.json
  config.json
  reference/track_exercises_overview.md
Labels: x:rep/large

#3479 [Gigasecond]: Update hints.md
  exercises/practice/gigasecond/.docs/hints.md
Labels: x:rep/tiny

#3481 [Gigasecond]: Correct Typo in Reflink for Hints file. Try 2
  exercises/practice/gigasecond/.docs/hints.md
Labels: x:rep/tiny
