Repository exercism/python, pull requests merged in 2024-01, with the labels that each got.

#3588 Update content.md with the correct link this time!
  exercises/practice/leap/.articles/performance/content.md
Labels: x:rep/tiny

#3593 [Leap]: Updated Table in Performance Article with Newer Timings to Match Graph.
  exercises/practice/leap/.articles/performance/content.md
Labels: x:rep/small

#3595 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#3598 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#3601 [Python Docs]: Update Python Version in INSTALLATION.md
  docs/INSTALLATION.md
Labels: x:rep/small

#3610 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
